"""Controlled, RNG-free uncertainty calculations for completed observations.

Exact Fraction moments and integer binomial tails precede irrational operations.
Decimal operations use fresh ROUND_HALF_EVEN contexts (80 significant digits,
extended by the number of df digits for log-gamma subtraction); new numeric
results serialize at 34 significant digits, matching existing aggregate ratios.
Neither the caller's Decimal context nor platform libm participates.
"""
from decimal import Context, Decimal, ROUND_HALF_EVEN, localcontext
from fractions import Fraction
from functools import lru_cache

from app.engine.numbers import decimal_text

PRECISION = 80
NORMAL_975 = Decimal("1.9599639845400542355245944305205515279555500778695")
LOG_TWO_PI = Decimal("1.837877066409345483560659472811235279722794947275566825634303080965531391854520795389486597271908")


def _context(precision=PRECISION):
    return Context(prec=precision, rounding=ROUND_HALF_EVEN)


def _decimal(value):
    value = Fraction(value)
    return Decimal(value.numerator) / Decimal(value.denominator)


def numeric_text(value):
    with localcontext(_context(34)):
        return str((+value).normalize()) if value else "0"


def probability_uncertainty(successes, size):
    """Wilson score inversion with fixed 50-significant-digit z; never a Wald interval."""
    if not 0 <= successes <= size or size < 1:
        raise ValueError("Probability requires 0 <= successes <= positive size")
    with localcontext(_context()):
        n = Decimal(size)
        p = _decimal(Fraction(successes, size))
        variance = _decimal(Fraction(successes * (size - successes), size ** 3))
        z2 = NORMAL_975 * NORMAL_975
        scale = 1 + z2 / n
        center = (p + z2 / (2 * n)) / scale
        radius = NORMAL_975 * (variance + z2 / (4 * n * n)).sqrt() / scale
        # The endpoint is exactly zero/one at the boundary, avoiding cancellation.
        lower = Decimal(0) if successes == 0 else max(Decimal(0), center - radius)
        upper = Decimal(1) if successes == size else min(Decimal(1), center + radius)
        return {"standard_error": numeric_text(variance.sqrt()),
                "confidence_interval": {"level": "0.95", "method": "wilson",
                                        "lower": numeric_text(lower), "upper": numeric_text(upper)}}


@lru_cache(maxsize=1)
def _stirling_coefficients():
    """Exact Bernoulli numbers B2..B96, generated by their rational recurrence."""
    from math import comb
    bernoulli = [Fraction(1)]
    for m in range(1, 97):
        bernoulli.append(-sum(Fraction(comb(m + 1, k)) * bernoulli[k]
                              for k in range(m)) / (m + 1))
    return tuple(bernoulli[k] / (k * (k - 1)) for k in range(2, 97, 2))


def _log_gamma(x):
    """Shift to x>=128 then use 48 Stirling terms, with <1e-110 remainder.

    This single algorithm applies for every df; there is no large-df normal
    approximation or critical-value table. The shift is a gamma identity.
    """
    correction = Decimal(0)
    while x < 128:
        correction += x.ln()
        x += 1
    inverse = 1 / x
    inverse2 = inverse * inverse
    series = Decimal(0)
    for coefficient in _stirling_coefficients():
        series += _decimal(coefficient) * inverse
        inverse *= inverse2
    return (x - Decimal("0.5")) * x.ln() - x + LOG_TWO_PI / 2 + series - correction


def _beta_fraction(a, b, x):
    """Incomplete-beta continued fraction via convergents, no tiny epsilon.

    Modified Lentz evaluation stops when the multiplier rounds to exactly one
    in the controlled context. For the positive beta parameters and interior
    evaluation points used here its denominators are nonzero. Explicit failure
    guards prevent silently substituting a result if convergence ever fails.
    """
    qab, qap, qam = a + b, a + 1, a - 1
    c = Decimal(1)
    d = 1 / (1 - qab * x / qap)
    h = d
    for m in range(1, 10001):
        m2 = 2 * m
        aa = m * (b - m) * x / ((qam + m2) * (a + m2))
        d = 1 / (1 + aa * d)
        c = 1 + aa / c
        h *= d * c
        aa = -(a + m) * (qab + m) * x / ((a + m2) * (qap + m2))
        d = 1 / (1 + aa * d)
        c = 1 + aa / c
        delta = d * c
        previous = h
        h *= delta
        if delta == 1 or h == previous:
            return h
    raise ArithmeticError("Incomplete beta did not converge")


def _central_t_probability(t, df, log_beta):
    a, b = Decimal("0.5"), Decimal(df) / 2
    x = t * t / (df + t * t)
    front = (a * x.ln() + b * (1 - x).ln() - log_beta).exp()
    if x < (a + 1) / (a + b + 2):
        return front * _beta_fraction(a, b, x) / a
    return 1 - front * _beta_fraction(b, a, 1 - x) / b


@lru_cache(maxsize=256)
def student_t_critical(df):
    """t(.975,df) for every positive integer df, deterministically.

    Solve I_[t²/(df+t²)](1/2,df/2)=.95 by 240 bisections on [0,16].
    All positive-integer df roots lie here (df=1 gives the largest root).
    The final bracket width is 16/2**240 (<1e-71). Return 60 significant
    decimal digits; public uncertainty values are rounded to 34 digits.
    Working precision grows with df digit count to protect gamma subtraction.
    """
    if not isinstance(df, int) or isinstance(df, bool) or df < 1:
        raise ValueError("Student-t degrees of freedom must be a positive integer")
    with localcontext(_context(PRECISION + len(str(df)))):
        b = Decimal(df) / 2
        log_beta = _log_gamma(Decimal("0.5")) + _log_gamma(b) - _log_gamma(b + Decimal("0.5"))
        lower, upper = Decimal(0), Decimal(16)
        for _ in range(240):
            middle = (lower + upper) / 2
            if _central_t_probability(middle, df, log_beta) < Decimal("0.95"):
                lower = middle
            else:
                upper = middle
        with localcontext(_context(60)):
            return +((lower + upper) / 2)


def mean_uncertainty(values):
    """Population SD, sample SD (ddof=1), mean SE and support-clipped t CI."""
    n = len(values)
    empty = {"standard_deviation": None, "sample_standard_deviation": None,
             "standard_error": None, "confidence_interval": None}
    if not n:
        return empty
    mean = sum(values, Fraction()) / n
    squared = sum(((value - mean) ** 2 for value in values), Fraction())
    with localcontext(_context()):
        empty["standard_deviation"] = numeric_text(_decimal(squared / n).sqrt())
        if n == 1:
            return empty
        se = _decimal(squared / (n * (n - 1))).sqrt()
        radius = student_t_critical(n - 1) * se
        lower, upper = _decimal(mean) - radius, _decimal(mean) + radius
        return {"standard_deviation": empty["standard_deviation"],
                "sample_standard_deviation": numeric_text(_decimal(squared / (n - 1)).sqrt()),
                "standard_error": numeric_text(se),
                "confidence_interval": {"level": "0.95", "method": "student_t",
                                        "degrees_of_freedom": n - 1, "lower_clipped": lower < 0,
                                        "lower": numeric_text(max(Decimal(0), lower)),
                                        "upper": numeric_text(upper)}}


@lru_cache(maxsize=256)
def quantile_ranks(n, p):
    """Equal-tailed exact binomial ranks, with inclusive tail boundaries.

    B~Bin(n,p). Choose greatest L with P(B<L)<=1/40 and smallest U with
    P(B>=U)<=1/40. Then [X_(L),X_(U)] has at least 95% coverage for a
    continuous population, conservatively with ties. Mathematical ranks are
    1-based; L=0 and U=n+1 are unavailable finite bounds, returned as None.
    Equality is accepted (<=), with NO rounded binomial-CDF comparisons.
    Integer mass recurrence computes numerator weights over denominator d**n.
    Reflect p>1/2 to reuse exact ranks; this is algebraic symmetry, not an
    approximation. Integer divisions are exact. No sampling or RNG occurs.
    """
    p = Fraction(p)
    if n < 0 or not 0 < p < 1:
        raise ValueError("Quantile ranks require n>=0 and 0<p<1")
    if p > Fraction(1, 2):
        lower, upper = quantile_ranks(n, 1 - p)
        return (n + 1 - upper if upper is not None else None,
                n + 1 - lower if lower is not None else None)
    a, d = p.numerator, p.denominator
    b = d - a
    denominator = d ** n
    mass = b ** n
    cumulative = 0
    lower = None
    for k in range(n + 1):
        cumulative += mass
        if lower is None and cumulative * 40 > denominator:
            lower = k
        if cumulative * 40 >= 39 * denominator:
            upper = k + 1
            return lower or None, upper if upper <= n else None
        mass = mass * (n - k) * a // ((k + 1) * b)
    raise ArithmeticError("Binomial rank selection failed")


def quantile_interval(sorted_values, p):
    lower, upper = quantile_ranks(len(sorted_values), p)
    return {"level": "0.95", "method": "binomial_order_statistic",
            "lower_rank": lower, "upper_rank": upper,
            "lower": decimal_text(sorted_values[lower - 1]) if lower is not None else None,
            "upper": decimal_text(sorted_values[upper - 1]) if upper is not None else None}
